# Generated by Django 5.1.1 on 2024-11-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognition',
            fields=[
                ('mssv', models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('id_card', models.CharField(default='unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_processing.facerecognition')),
            ],
        ),
    ]
